-- ============================================================
-- 建表 SQL：人员管理 staff_list
-- 在 Supabase SQL Editor 中执行此脚本
-- ============================================================

CREATE TABLE IF NOT EXISTS public.staff_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 索引（按姓名去重查询）
CREATE INDEX IF NOT EXISTS idx_staff_list_name ON public.staff_list(name);

-- RLS 策略（允许所有已认证用户读写）
ALTER TABLE public.staff_list ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许所有已认证用户查看人员" ON public.staff_list
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "允许所有已认证用户插入人员" ON public.staff_list
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "允许所有已认证用户更新人员" ON public.staff_list
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "允许所有已认证用户删除人员" ON public.staff_list
  FOR DELETE USING (auth.role() = 'authenticated');

-- 插入默认人员（与代码中 DEFAULT_STAFF_BASE 一致）
INSERT INTO public.staff_list (name, is_default) VALUES
  ('陈育婷', TRUE),
  ('蔡丹媛', TRUE),
  ('蔡中卫', TRUE),
  ('林沐锟', TRUE),
  ('丁小梅', TRUE),
  ('林晓媛', TRUE)
ON CONFLICT DO NOTHING;
