-- ============================================
-- 星堡移印样品仓储系统 - Supabase 数据库 Schema
-- 请在 Supabase SQL Editor 中执行以下 SQL
-- ============================================

-- 1. 创建 samples 表
CREATE TABLE IF NOT EXISTS public.samples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT DEFAULT '移印样品',
  location TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  status TEXT DEFAULT 'in_stock' CHECK (status IN ('in_stock', 'out_stock', 'reserved')),
  image_url TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 创建索引加速查询
CREATE INDEX IF NOT EXISTS idx_samples_code ON public.samples(code);
CREATE INDEX IF NOT EXISTS idx_samples_name ON public.samples(name);
CREATE INDEX IF NOT EXISTS idx_samples_category ON public.samples(category);
CREATE INDEX IF NOT EXISTS idx_samples_status ON public.samples(status);
CREATE INDEX IF NOT EXISTS idx_samples_location ON public.samples(location);
CREATE INDEX IF NOT EXISTS idx_samples_created_at ON public.samples(created_at DESC);

-- 3. 启用 Row Level Security (RLS)
ALTER TABLE public.samples ENABLE ROW LEVEL SECURITY;

-- 4. 创建 RLS 策略 - 允许认证用户读取所有数据
CREATE POLICY "允许认证用户读取" ON public.samples
  FOR SELECT
  TO authenticated
  USING (true);

-- 5. 允许认证用户插入数据
CREATE POLICY "允许认证用户插入" ON public.samples
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- 6. 允许认证用户更新数据
CREATE POLICY "允许认证用户更新" ON public.samples
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 7. 允许认证用户删除数据
CREATE POLICY "允许认证用户删除" ON public.samples
  FOR DELETE
  TO authenticated
  USING (true);

-- 8. 启用 Realtime 订阅（用于多人实时编辑）
ALTER PUBLICATION supabase_realtime ADD TABLE public.samples;

-- 9. 创建 Storage Bucket 用于图片存储
-- 请在 Supabase Dashboard -> Storage 中手动创建名为 "samples" 的 bucket
-- 并设置其权限为公开（public）

-- 10. 插入一些示例数据
INSERT INTO public.samples (code, name, category, location, quantity, status, notes) VALUES
('XB20240101001', '移印样品-A001', '移印样品', 'A区-01号柜', 5, 'in_stock', '标准移印样品'),
('XB20240101002', '丝印样品-B001', '丝印样品', 'B区-02号柜', 3, 'in_stock', '丝网印刷样品'),
('XB20240101003', '烫金样品-C001', '烫金样品', 'C区-01号柜', 2, 'out_stock', '已发给客户'),
('XB20240101004', '移印样品-A002', '移印样品', 'A区-02号柜', 10, 'in_stock', '批量移印样品'),
('XB20240101005', '特殊样品-D001', '其他', 'D区-03号柜', 1, 'reserved', '客户预约查看');

-- ============================================
-- 11. 仓储人员列表（所有用户实时同步）
-- ============================================
CREATE TABLE IF NOT EXISTS public.staff_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_staff_list_name ON public.staff_list(name);

ALTER TABLE public.staff_list ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许认证用户读取人员" ON public.staff_list
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "允许认证用户添加人员" ON public.staff_list
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "允许认证用户删除人员" ON public.staff_list
  FOR DELETE TO authenticated USING (is_default = false);

-- 启用 Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.staff_list;

-- 预填默认人员
INSERT INTO public.staff_list (name, is_default) VALUES
  ('陈育婷', true),
  ('蔡丹媛', true),
  ('蔡中卫', true),
  ('林沐锟', true),
  ('丁小梅', true),
  ('林晓媛', true)
ON CONFLICT (name) DO NOTHING;